WebApplication1/Models/CosModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class CosModel
    {
        [Key]
        public int Id_Cos { get; set; }
        public int Id_Produs { get; set; }
        public string Nume_Produs { get; set; }
        public int Cantitate_Produs { get; set; }
    }
    public class CosDbContext:DbContext
    {
        public DbSet<CosModel> Cos { get; set; }
    }
}

WebApplication1/Models/StocModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;
using WebApplication1.Models;

namespace WebApplication1.Models
{
    public class StocModel
    {
        [Key]
        public int Id_Produs { get; set; }
        public string Nume_Produs { get; set; }
        public string Material_Produs { get; set; }
        public int Cantitate_Produs { get; set; }
    }
    public class StocDbContext : DbContext
    {
        public DbSet<StocModel> Stoc { get; set; }
    }
    
}

WebApplication1/Controllers/CosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CosController : Controller
    {
        private CosDbContext dbCos = new CosDbContext();
        // GET: Cos
        public ActionResult Index()
        {
            return View(dbCos.Cos.ToList());
        }
        [HttpGet]
        public ActionResult DeleteProdus(int? id)
        {
            CosModel msg = dbCos.Cos.Find(id);
            return View(msg);
        }
        [HttpPost]
        public ActionResult DeleteProdus(int id)
        {
            using (CosDbContext dbCos = new CosDbContext())
            {
                using (StocDbContext dbStoc = new StocDbContext())
                {
                    CosModel msg = dbCos.Cos.Find(id);
                    dbCos.Cos.Remove(msg);
                    dbCos.SaveChanges();
                    
                    StocModel msg1 = dbStoc.Stoc.Find(msg.Id_Produs);

                    msg1.Cantitate_Produs = msg1.Cantitate_Produs + msg.Cantitate_Produs;
                    dbStoc.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            CosModel msg = dbCos.Cos.Find(id);
            return View(msg);
        }
        [HttpPost]
        public ActionResult Edit(CosModel msg)
        {
            
                    dbCos.Entry(msg).State = System.Data.Entity.EntityState.Modified;
                    dbCos.SaveChanges();
                    return RedirectToAction("Index ");
                
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication1/Controllers/StocController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class StocController : Controller
    {
        // GET: Stoc
        private StocDbContext dbStoc=new StocDbContext();
        public ActionResult Index()
        {
            return View(dbStoc.Stoc.ToList());
        }
        [HttpGet]
        public ActionResult Create()
        {
            StocModel msg = new StocModel();
            return View(msg);
        }
        [HttpPost]
        public ActionResult Create(StocModel msg)
        {
            dbStoc.Stoc.Add(msg);
            dbStoc.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult Details(int? id)
        {
            StocModel msg = dbStoc.Stoc.Find(id);
            return View(msg);
        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            StocModel msg = dbStoc.Stoc.Find(id);
            return View(msg);
        }
        [HttpPost]
        public ActionResult Edit(StocModel msg)
        {
            dbStoc.Entry(msg).State = System.Data.Entity.EntityState.Modified;
            dbStoc.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            StocModel msg = dbStoc.Stoc.Find(id);
            return View(msg);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            StocModel msg = dbStoc.Stoc.Find(id);
            dbStoc.Stoc.Remove(msg);
            dbStoc.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult  AdaugaLaCosulDeCumparaturi(int? id)
        {
            StocModel msg = dbStoc.Stoc.Find(id);
            return View(msg);
        }
        [HttpPost]
        public ActionResult AdaugaLaCosulDeCumparaturi(CosModel msg)
        {
            using (CosDbContext dbCos=new CosDbContext())
            {
                using (StocDbContext dbStoc = new StocDbContext())
                {
                    dbCos.Cos.Add(msg);
                    dbCos.SaveChanges();
                    StocModel msg1 = dbStoc.Stoc.Find(msg.Id_Produs);
                    msg1.Cantitate_Produs=msg1.Cantitate_Produs-msg.Cantitate_Produs;
                    dbStoc.SaveChanges() ;
                }
                
            }
            
            
            return RedirectToAction("Index");
        }
    }
}

WebApplication1/Views/Cos/DeleteProdus.cshtml
@model WebApplication1.Models.CosModel

@{
    ViewBag.Title = "DeleteProdus";
}

<h2>DeleteProdus</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CosModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id_Produs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id_Produs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nume_Produs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nume_Produs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantitate_Produs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantitate_Produs)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/Cos/Edit.cshtml
@model WebApplication1.Models.CosModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CosModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_Cos)

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Produs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id_Produs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id_Produs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nume_Produs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nume_Produs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nume_Produs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cantitate_Produs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantitate_Produs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantitate_Produs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Cos/Index.cshtml
@model IEnumerable<WebApplication1.Models.CosModel>

@{
    ViewBag.Title = "Cos de Cumparaturi";
}

<h2>Cos de Cumparaturi</h2>

<p>
    @Html.ActionLink("Adauga un produs la cosul de cumparaturi", "Index","Stoc")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id_Produs)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nume_Produs)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cantitate_Produs)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id_Produs)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nume_Produs)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cantitate_Produs)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new {  id=item.Id_Cos }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id_Cos }) |
            @Html.ActionLink("Elimina din cosul de cumparaturi", "DeleteProdus", new { id = item.Id_Cos })
        </td>
    </tr>
}

</table>

WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fitze la Rafa", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    <li>@Html.ActionLink("Stoc", "Index", "Stoc")</li>
                    <li>@Html.ActionLink("Cos", "Index", "Cos")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Stoc/AdaugaLaCosulDeCumparaturi.cshtml
@model WebApplication1.Models.StocModel

@{
    ViewBag.Title = "AdaugaLaCosulDeCumparaturi";
}

<h2>AdaugaLaCosulDeCumparaturi</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_Produs)

        <div class="form-group">
            @Html.LabelFor(model => model.Nume_Produs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nume_Produs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nume_Produs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Material_Produs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Material_Produs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Material_Produs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cantitate_Produs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantitate_Produs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantitate_Produs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Stoc/Create.cshtml
@model WebApplication1.Models.StocModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StocModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nume_Produs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nume_Produs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nume_Produs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Material_Produs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Material_Produs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Material_Produs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cantitate_Produs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantitate_Produs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantitate_Produs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Stoc/Delete.cshtml
@model WebApplication1.Models.StocModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StocModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nume_Produs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nume_Produs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Material_Produs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Material_Produs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantitate_Produs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantitate_Produs)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/Stoc/Details.cshtml
@model WebApplication1.Models.StocModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>StocModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nume_Produs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nume_Produs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Material_Produs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Material_Produs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantitate_Produs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantitate_Produs)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id_Produs }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication1/Views/Stoc/Edit.cshtml
@model WebApplication1.Models.StocModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StocModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_Produs)

        <div class="form-group">
            @Html.LabelFor(model => model.Nume_Produs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nume_Produs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nume_Produs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Material_Produs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Material_Produs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Material_Produs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cantitate_Produs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantitate_Produs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantitate_Produs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Stoc/Index.cshtml
@model IEnumerable<WebApplication1.Models.StocModel>

@{
    ViewBag.Title = "Stoc Produse";
}

<h2>Stoc Produse</h2>

<p>
    @Html.ActionLink("Adauga un nou produs", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nume_Produs)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Material_Produs)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cantitate_Produs)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nume_Produs)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Material_Produs)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cantitate_Produs)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id_Produs }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id_Produs }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id_Produs }) |
            @Html.ActionLink("Adauga la cosul de cumparaturi", "AdaugaLaCosulDeCumparaturi", new { id = item.Id_Produs })
        </td>
    </tr>
}

</table>